// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let notExceed = 4000000;

function arrList(arr) {
  for (let i = 0; i < arr.length; i++) {
    if (
      arr[arr.length - 1] < notExceed &&
      arr[arr.length - 1] + arr[arr.length - 2] < notExceed
    ) {
      arr.push(arr[i] + arr[i + 1]);
    }
  }
  console.log(arr);
  return sumValuedEven(arr);
}

function sumValuedEven(arr) {
  let sum = 0;
  for (let i = 0; i < arr.length; i++) {
    if (arr[i] % 2 == 0) sum += arr[i];
  }
  return sum;
}

console.log(arrList([1, 2]));
